### ISSUE TITLE
Can't find the package imported

### ISSUE THREAD

**Issue by Olyno** [pkovzz/ngx-otp-input#16]
**Describe the bug**

It looks like i can't import the package because this one doesn't export ``main``. Getting this error from Angular:
```
Module not found: Error: Package path . is not exported from package /project/node_modules/ngx-otp-input (see exports field in project/node_modules/ngx-otp-input/package.json)
```

**To Reproduce**

Simply tried to import the package.

**Expected behavior**

We should be able to import the package.

**Desktop (please complete the following information):**

- Browser [e.g. chrome, safari] Firefox

**Additional context**

Angular version: ``^14.0.0``

**Comment by vve7s** [comment]
I have the same problem

**Comment by k2peter** [comment]
Could you show an example code please?

**Comment by Olyno** [comment]
Generating a new Angular project, and importing the module in ``app.module.ts`` should be enough to see the error

**Comment by k2peter** [comment]
@Olyno I asked it because the examples on vercel and stackblitz are working fine, and those apps are on Angular 14+. I'll bootstrap a new Angular app on my machine and give it a look soon.

@gergelypap could you provide more information please?

**Comment by gergelypap** [comment]
@k2peter I didn't investigate the TS errors too much, maybe it was a project-specific configuration from my side. Eventually I decided to ditch this project in favor of [ng-otp-input](https://www.npmjs.com/package/ng-otp-input).

**Comment by tanoabeleyra** [comment]
Any updates on this? I'm still seeing this error on Angular 14.

**Comment by pkovzz** [comment]
Hi @tanoabeleyra!

I'm sorry for being silent this long. I managed to reproduce the error, and I'm working on a fix now! I will post here if the fix is published.

**Comment by pkovzz** [comment]
Version **0.11.4** has the fix, please try it! Any feedback is welcome.

**Comment by pkovzz** [comment]
Great! If you notice any other issue, please open a new issue for it.
