### ISSUE TITLE
Failed to install on angular 13

### ISSUE THREAD

**Issue by MariaAlmeidaMJ** [pkovzz/ngx-otp-input#17]
<img width="587" alt="Captura de ecrã 2023-01-09, às 16 40 29" src="https://user-images.githubusercontent.com/60096770/211362726-f6368f24-69c8-4a1c-be49-94d3ae0e5a2d.png">

When I try to install this library in angular 13 project it is giving me the error visible in the image
I tried to install the version that I saw would be compatible. I added this on package.json `"ngx-otp-input": "0.11.1"` and made an `npm update `
Can you check this for me ASAP? Thanks

**Comment by pkovzz** [comment]
Hi @MariaAlmeidaMJ!
Could you try please the latest version? 
Also, if you need _ASAP_, `--force` or `--legacy-peer-deps` npm install commands can fix the problem temporary.

**Comment by MariaAlmeidaMJ** [comment]
@pkovzz I can't use the latest version because it uses angular 14 and I want to avoid using "--force" or "--legacy-peer-deps"

**Comment by MariaAlmeidaMJ** [comment]
Any news about this problem?

**Comment by pkovzz** [comment]
A [new version](https://github.com/pkovzz/ngx-otp-input/releases/tag/v1.0.0) has been released, and it requires Angular 14 as a minimum version.
