### ISSUE TITLE
Mobile-device input-focus change not working

### ISSUE THREAD

**Issue by partharamanujam** [pkovzz/ngx-otp-input#18]
**Describe the bug**
The input-focus is not changing on user input

**To Reproduce**
Please refer to https://github.com/pkovzz/ngx-otp-input/issues/6

**Expected behavior**
Input-focus moves to next box after correct input

**Screenshots**
Please refer to https://github.com/pkovzz/ngx-otp-input/issues/6

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Chrome 
- Android-11

**Additional context**
The issue https://github.com/pkovzz/ngx-otp-input/issues/6 was closed. There is a reference to https://ngx-otp-input-j6iwwfgom-pkovzz.vercel.app/ which seems to work properly on Android-11 device. Please help share details/approach to resolve the issue; maybe a good idea to add this to the documentation for further reference to other users.

**Comment by pkovzz** [comment]
Hi @partharamanujam!
I'm sorry, but I'm afraid I do not fully understand your issue here. You wrote as a context that the feature works correctly, right?

**Comment by partharamanujam** [comment]
Issue https://github.com/pkovzz/ngx-otp-input/issues/6 is observed when module is installed using "npm install".
However, the same issue is not observed in the example deployment at  https://ngx-otp-input-j6iwwfgom-pkovzz.vercel.app/

Need help to clarify the settings/configurations used to setup above example. As mentioned earlier,  it maybe a good idea to add this to the documentation for further reference to other users.

**Comment by pkovzz** [comment]
Thank you for bringing this bug to my attention. While I'm currently focusing on other priorities, I do plan to address this issue in the near future. Your patience is greatly appreciated as I work to improve my project. If you have any further feedback or concerns, please don't hesitate to let me know. Thank you for your support of my open-source project.

**Comment by pkovzz** [comment]
A [new version](https://github.com/pkovzz/ngx-otp-input/releases/tag/v1.0.0) has been released, and this functionality has been fixed. I have noticed, that there are more rooms for improvements regarding of mobile experience, more updates coming soon.
