### ISSUE TITLE
Autocomplete Off is not working

### ISSUE THREAD

**Issue by Shreyabhanot** [pkovzz/ngx-otp-input#19]
**Describe the bug**
Not able to turn off the auto-complete for ngx-otp-input

**To Reproduce**
Not able to turn off the autocomplete for ngx-otp-input by using several below methods -:

1. autocomplete = "off"
2. autocomplete = "new-password"
3.  By making custom directive for disabling the autocomplete
4. By creating a similar input field and setting it to display:none

**Expected behavior**
It should not give the suggestion list for ngx-otp-input

**Screenshots**
![image](https://user-images.githubusercontent.com/40555678/232755738-0101c44c-2f48-4e81-99aa-e76a151c6b0b.png)

**Desktop (please complete the following information):**

- Browser Chrome
- Version 108.0.5359.125

**Comment by pkovzz** [comment]
Hey @Shreyabhanot!
Thanks for opening the issue. Could you reproduce the same behavior in other browsers too? Chrome tends to ignore the autocomplete="off" attribute.

**Comment by Shreyabhanot** [comment]
Hey @pkovzz !
It was not working because ngx-otp-input is only a wrapper for input elements. Resolved by manipulating the inside input elements.
Check the below link for the resolution
https://stackoverflow.com/questions/76051809/not-able-to-turn-off-auto-complete-for-ngx-otp-input-in-angular

**Comment by wescleysrn** [comment]
Hello @Shreyabhanot and @pkovzz 

I am experiencing the same problem, I noticed that if I include in the settings isPasswordInput: true the auto complete stops occurring as expected. And as described in this link:

https://pt.stackoverflow.com/questions/61510/como-remover-auto-complete-de-input-do-google-chrome

In current versions of Google Chrome it is possible to solve this if autocomplete="off" is in the form tag.

Suggestion:

Modify the file receiving the boolean autocomplete definition received from the NgxOtpInputConfig interface.
https://github.com/pkovzz/ngx-otp-input/blob/master/projects/ngx-otp-input/src/lib/component/ngx-otp-input.component.html

Modify the file by making the NgxOtpInputConfig interface have the autocomplete configuration property.
https://github.com/pkovzz/ngx-otp-input/blob/master/projects/ngx-otp-input/src/lib/component/ngx-otp-input.model.ts

Does that make sense to you? Is this a good approach to solving the problem?

**Comment by pkovzz** [comment]
Hello @wescleysrn!

Thank you very much for your effort to fix this issue. To be honest, I'm not really satisfied with the current state of the library, so I've decided to rewrite it in the near future, including this and other fixes as well. Since I can't tell you exactly when this will happen, if you have a strict deadline, I suggest checking other OTP libraries too.
