### ISSUE TITLE
accepts some Arabic letters 

### ISSUE THREAD

**Issue by lamaCS** [pkovzz/ngx-otp-input#22]
**Describe the bug**
otp field accepts some Arabic alef variation such as [ا, أ]

**To Reproduce**
1- Convert your keyboard to Arabic 
2. Click on 'B' button with or without shift
3. Click on 'G' button with shift
4. Click on 'T' button with shift

**Expected behavior**
otp should not accepts it 

**Screenshots**
![image](https://github.com/pkovzz/ngx-otp-input/assets/66234085/2d46486f-7ee2-40aa-a236-d45665b6a82f)

- Browser: chrome
- Version: latest

**Additional context**
my config: 
  otpInputConfig: NgxOtpInputConfig = {
    otpLength: 4,
    numericInputMode: true,
  };

**Comment by haljassar** [comment]
I faced the same issue. Have you resolved it?

**Comment by pkovzz** [comment]
Hi @haljassar,
Please check my comment [here](https://github.com/pkovzz/ngx-otp-input/issues/19#issuecomment-2118675624).

**Comment by haljassar** [comment]
Thank you @pkovzz , I appreciate your quick reply.

**Comment by pkovzz** [comment]
A [new version](https://github.com/pkovzz/ngx-otp-input/releases/tag/v1.0.0) has been released. With [RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp), the library should block these characters now. If not, please re-open the issue. Thanks4
