### ISSUE TITLE
Does not work on Android devices: undefined instead of pressed key

### ISSUE THREAD

**Issue by LukasKlement** [pkovzz/ngx-otp-input#27]
**Describe the bug**
In version 1.1, clicking any key on an Android device sets the code input in inputMode text to "undefined", whereas it worked fine in version 0.11.4

**Expected behavior**
The key that was pressed should be entered in the code input field.

**Screenshots**

**Smartphone**

- Browser Chrome
- Version 127

**Comment by pkovzz** [comment]
Hi @LukasKlement!
I need a little bit more information. Can you reproduce the issue on the demo site too? If so, could you record your screen as well? Thanks in advance!

**Comment by LukasKlement** [comment]
Hi @pkovzz, sure, here is a recording: https://share.zight.com/nOu7AplP
Android Emulator on macOS with Pixel Fold; I can reproduce the same on physical devices.

**Comment by pkovzz** [comment]
@LukasKlement, I've deployed a fix. Could you please verify, that everything is working as expected? You can find the deployment [here](https://ngx-otp-input-qfkjsn39g-pkovzzs-projects.vercel.app).

**Comment by LukasKlement** [comment]
@pkovzz thanks for the new version. I QA'ed it, it's working perfectly fine now, on iOS and Android: https://share.zight.com/eDuZQ58G

**Comment by pkovzz** [comment]
@LukasKlement thanks for your help! I've merged the fix and published it in version 1.1.1 .
