### ISSUE TITLE
OtpComplete emits multiple values after paste

### ISSUE THREAD

**Issue by Guslarz** [pkovzz/ngx-otp-input#29]
**Describe the bug**
If ngx-otp-input is already filled and user pastes some other value otpComplete Output emits multiple values, one for each input that has different value before and after paste.  

**To Reproduce**
1. Enter some valid otp value e.g "000000" for 6 digit otp input
2. Paste another otp e.g. "111111"
3.  OtpComplete emits multiple values, "100000", "110000", "111000" etc. for given example values

**Expected behavior**
OtpComplete should emit only one value

**Comment by pkovzz** [comment]
Hi @Guslarz!
Sorry for the really late answer, I will ship a fix in the near future.
