### ISSUE TITLE
bug - ERROR TypeError: Cannot read properties of undefined (reading 'setValue')

### ISSUE THREAD

**Issue by wizardnet972** [pkovzz/ngx-otp-input#31]
When I paste "12345678" into an input field with only five input boxes, I encounter this error in the console:

```
ERROR TypeError: Cannot read properties of undefined (reading 'setValue')
```

The error occurs on this line:  
```
this.ngxOtpInputArray.controls[index].setValue(value);
```
https://github.com/pkovzz/ngx-otp-input/blob/master/projects/ngx-otp-input/src/lib/ngx-otp-input.component.ts#L133

This happens because the code iterates over all characters in the input, exceeding the number of available input boxes.

<img width="1121" alt="image" src="https://github.com/user-attachments/assets/0f4d7760-4c8e-4bcb-9b34-c0abde9ebe4c">

**Comment by pkovzz** [comment]
Hi @wizardnet972,
Thank you so much for your contribution! 🎉 
Your fix has been included in the latest release (v1.1.3). I truly appreciate your effort in improving the project.
If you have any more ideas or suggestions, feel free to share them. Thanks again for your support!
