### ISSUE TITLE
Continues OTP changes not working.

### ISSUE THREAD

**Issue by jitendra-huma** [pkovzz/ngx-otp-input#4]
Continues OTP changes should work. now if I entered 333333. and when I change it to 444444 so at that moment manually focus on input.

**Comment by pkovzz** [comment]
It works as intended. Usually after fill event, the app should send automatically the otp code to the server or something. But I can imagine a scenario where you may want to fire this event by click for example.

I will extend the current API with a new option, which will determinate the behavior of the final event.
