### ISSUE TITLE
dynamic Autofocus 

### ISSUE THREAD

**Issue by Swapnali1010** [pkovzz/ngx-otp-input#5]
On my device , plugin install properly , but after first input box entry second input box is not getting focus , i have to manually click on next input for next digit 
device : Samsung A10
OS : Android 
version : 10

**Comment by pkovzz** [comment]
Can you reproduce the described behaviour in the demo app too? https://ngx-otp-input.vercel.app/

**Comment by pkovzz** [comment]
I close the issue due to inactivity.
