### ISSUE TITLE
In mobile device input focus not working.

### ISSUE THREAD

**Issue by Nitekurs** [pkovzz/ngx-otp-input#6]

**Comment by pkovzz** [comment]
Hi!

Could you provide me a more detailed description please?
I can't reproduce the bug.



https://user-images.githubusercontent.com/38242358/130086228-72a75874-d704-40f6-bd95-bbfcfe6219ec.MP4

**Comment by Nitekurs** [comment]
@pkovzz, In my device (android 11) if open this link https://ngx-otp-input.vercel.app/  on input edit, focus on next input not working.
Please see this attached video.
https://user-images.githubusercontent.com/48058350/130114236-3d00b593-b65c-4d2f-99b5-8d12e7468d9a.mp4

**Comment by pkovzz** [comment]
@Nitekurs this is an interesting bug. Unfortunately, I don't have physical Android device, but I tested the component on an emulated Pixel 3, and it worked on it. I will looking for a solution, but I can't promise anything.

**Comment by pkovzz** [comment]
@Nitekurs, could you check this versions please? 
https://ngx-otp-input-j6iwwfgom-pkovzz.vercel.app/
