### ISSUE TITLE
Input not disabled when disable option are true

### ISSUE THREAD

**Issue by akbarsaputrait** [pkovzz/ngx-otp-input#7]
**Describe the bug**
Input doesn't disabled when disable option are true

**To Reproduce**
1. Set `[disable]="true"`
2. Input still can be typed

**Screenshots**
![image](https://user-images.githubusercontent.com/27531592/130072665-1cd6d1c5-bccf-47e8-a0d8-5ae0ccdda313.png)

**Desktop (please complete the following information):**
 - Browser => Chrome 92.0.4515.159
 - Version => ^0.9.0

**Comment by pkovzz** [comment]
Fixed. Can you reproduce the bug here?
https://stackblitz.com/edit/angular-ngx-otp-input-czp6qq
