### ISSUE TITLE
Page jump in iphone on edit. iOS 12

### ISSUE THREAD

**Issue by Nitekurs** [pkovzz/ngx-otp-input#8]
**To Reproduce**
1. Create angular based project open link in iOS device below 12 version.
2. On input edit pages are jumping.
3. https://user-images.githubusercontent.com/48058350/130113514-0e13aa77-071f-46ce-83bd-38cef8b99924.mp4

**Smartphone (please complete the following information):**
 - Browser - safari
 - Version - iOS 12

**Comment by pkovzz** [comment]
@Nitekurs sorry, but iOS 12 is a really old version of iOS and this bug won't be fixed. iOS 12's market share is below 2% according to this [site](https://developer.apple.com/support/app-store/).

**Comment by Nitekurs** [comment]
> @Nitekurs sorry, but iOS 12 is a really old version of iOS and this bug won't be fixed. iOS 12's market share is below 2% according to this [site](https://developer.apple.com/support/app-store/).

@pkovzz Is there any alternate solution available for this ? or Is there any other library available for this that you know?

**Comment by pkovzz** [comment]
> > @Nitekurs sorry, but iOS 12 is a really old version of iOS and this bug won't be fixed. iOS 12's market share is below 2% according to this [site](https://developer.apple.com/support/app-store/).
> 
> @pkovzz Is there any alternate solution available for this ? or Is there any other library available for this that you know?

[Maybe this one.](https://www.npmjs.com/package/ng-otp-input)

**Comment by Nitekurs** [comment]
> > > @Nitekurs sorry, but iOS 12 is a really old version of iOS and this bug won't be fixed. iOS 12's market share is below 2% according to this [site](https://developer.apple.com/support/app-store/).
> > 
> > 
> > @pkovzz Is there any alternate solution available for this ? or Is there any other library available for this that you know?
> 
> [Maybe this one.](https://www.npmjs.com/package/ng-otp-input)

Hehehe, Same issue here also. Thanks

**Comment by pkovzz** [comment]
> > > > @Nitekurs sorry, but iOS 12 is a really old version of iOS and this bug won't be fixed. iOS 12's market share is below 2% according to this [site](https://developer.apple.com/support/app-store/).
> > > 
> > > 
> > > @pkovzz Is there any alternate solution available for this ? or Is there any other library available for this that you know?
> > 
> > 
> > [Maybe this one.](https://www.npmjs.com/package/ng-otp-input)
> 
> Hehehe, Same issue here also. Thanks

Yeah, it looks like an OS related problem, rather than the library.
